### ISSUE TITLE
firecombostream collision error

### ISSUE THREAD

**Issue by PhanaticD** [PhanaticD/ProjectKorra#4]
```
[04:53:45] [Server thread/WARN]: [ProjectKorra] Task #87405 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.collision(FireComboStream.java:139) ~[?:?]
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.run(FireComboStream.java:98) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[04:53:45] [Server thread/WARN]: [ProjectKorra] Task #87406 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.collision(FireComboStream.java:139) ~[?:?]
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.run(FireComboStream.java:98) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[04:53:45] [Server thread/WARN]: [ProjectKorra] Task #87406 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.collision(FireComboStream.java:139) ~[?:?]
    at com.projectkorra.projectkorra.firebending.combo.FireComboStream.run(FireComboStream.java:98) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by PhanaticD** [comment]
possibly related firemanipulation errors with collision

```
[08:04:17] [Server thread/WARN]: [ProjectKorra] Task #84 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:217) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:213) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[08:04:18] [Server thread/WARN]: [ProjectKorra] Task #84 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:217) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:213) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[08:04:18] [Server thread/INFO]: FIN4 issued server command: /home
[08:04:18] [Server thread/WARN]: [ProjectKorra] Task #84 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:217) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:213) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[08:04:19] [Server thread/WARN]: [ProjectKorra] Task #84 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:217) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:213) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[08:04:19] [Server thread/INFO]: ICodeI issued server command: /chest
[08:04:22] [Async Chat Thread - #38/INFO]: [Fire] ?Sneaky? ~Yojo [M]: wmahaha
[08:04:23] [Async Chat Thread - #38/INFO]: [Avatar] iElite ~Lovely [M]: let me
[08:04:23] [Server thread/INFO]: ICodeI issued server command: /chest
[08:04:26] [Server thread/INFO]: FIN4 issued server command: /warp spawngrinder
[08:04:28] [Server thread/WARN]: [ProjectKorra] Task #84 for ProjectKorra v1.8.8 generated an exception
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.firebending.FireManipulation.getLocations(FireManipulation.java:217) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.detectCollisions(CollisionManager.java:104) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager.access$000(CollisionManager.java:36) ~[?:?]
    at com.projectkorra.projectkorra.ability.util.CollisionManager$1.run(CollisionManager.java:213) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by PhanaticD** [comment]
"That's from JetBlaze because the FireComboStreams still persist after JetBlaze ends. If you damage an entity as JetBlaze is ending, you can trigger it."
