### ISSUE TITLE
temparmor npe

### ISSUE THREAD

**Issue by PhanaticD** [PhanaticD/ProjectKorra#9]
```
[16:27:27] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ProjectKorra v1.8.8
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.util.TempArmor.filterArmor(TempArmor.java:114) ~[?:?]
    at com.projectkorra.projectkorra.PKListener.onEntityDeath(PKListener.java:464) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor773.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-528]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntitySkeleton.die(EntitySkeleton.java:42) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274) ~[patched_1.13.2.jar:git-Paper-528]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:65) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:95) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:99) ~[?:?]
    at com.phanaticmc.fireuppercut.FireUppercut.<init>(FireUppercut.java:46) ~[?:?]
    at com.phanaticmc.fireuppercut.FireUppercutListener.onSneak(FireUppercutListener.java:22) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor743.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-528]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1854) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-528]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
    at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by PhanaticD** [comment]
after update:

```
[18:10:33] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ProjectKorra v1.8.8
java.lang.NullPointerException: null
    at com.projectkorra.projectkorra.util.TempArmor.filterArmor(TempArmor.java:114) ~[?:?]
    at com.projectkorra.projectkorra.PKListener.onEntityDeath(PKListener.java:454) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor773.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-528]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntitySkeleton.die(EntitySkeleton.java:42) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274) ~[patched_1.13.2.jar:git-Paper-528]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:65) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:95) ~[?:?]
    at com.projectkorra.projectkorra.util.DamageHandler.damageEntity(DamageHandler.java:99) ~[?:?]
    at com.phanaticmc.fireuppercut.FireUppercut.<init>(FireUppercut.java:46) ~[?:?]
    at com.phanaticmc.fireuppercut.FireUppercutListener.onSneak(FireUppercutListener.java:22) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor743.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-528]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-528]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1854) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-528]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
    at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-528]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-528]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by PhanaticD** [comment]
happens when entity is killed while in earthgrab
